version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "8000-8000"
    volumes:
      - ./core:/core
      - dev-static-data:/vol/web
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./loc.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
volumes:
  dev-db-data:
  dev-static-data:
