version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "8000-8000"
    volumes:
      - ./core:/core
      - dev-static-data:/vol/web
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./loc.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass

  celery:
    build:
     context: .
    command: celery worker --app=core --loglevel=info
    volumes:
      - ./core:/core
    env_file:
      - ./loc.env

    depends_on:
      - app
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build:
      context: .
    command:  flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./loc.env

    depends_on:
      - app
      - redis
      - celery

volumes:
  dev-db-data:
  dev-static-data:
