# Generated by Django 3.2.16 on 2022-12-17 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtype', models.CharField(choices=[('EASY', 'Easy run'), ('ENDURANCE', 'Endurance run'), ('TEMPO', 'Tempo run'), ('INTERVALS', 'Interval run'), ('UNCATEGORISED', 'Uncagetorised run')], default='UNCATEGORISED', max_length=13)),
                ('date', models.DateField()),
                ('units', models.CharField(choices=[('KM', 'Kilometres'), ('MI', 'Miles')], default='KM', max_length=2)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('pace', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_HR', models.IntegerField(null=True)),
                ('notes', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtype', models.CharField(choices=[('EASY', 'Easy run'), ('ENDURANCE', 'Endurance run'), ('TEMPO', 'Tempo run'), ('INTERVALS', 'Interval run'), ('UNCATEGORISED', 'Uncagetorised run')], default='UNCATEGORISED', max_length=13)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
