# Generated by Django 3.2.16 on 2022-12-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_alter_plan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
