# Generated by Django 3.2.16 on 2022-12-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_alter_run_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
